### ISSUE TITLE
Testing: Why use pytest instead of unittest?

### ISSUE THREAD

**Issue by Joe-Heffer-Shef** [RSE-Sheffield/team-python#13]
My question: what are the advantages of using [pytest](https://docs.pytest.org/en/7.2.x/) rather than the inbuilt [unittest](https://docs.python.org/3/library/unittest.html) library?

Does it help implement testing best practices and methodologies?

Why would I install `pytest` when `unittest` is built in to the core libraries?

What can I do with `pytest` that I can't do with other libraries?

Pytest claims:
> The pytest framework makes it easy to write small, readable tests, and can scale to support complex functional testing for applications and libraries.

`unittest` claims:
> The [unittest](https://docs.python.org/3/library/unittest.html#module-unittest) unit testing framework was originally inspired by JUnit and has a similar flavor as major unit testing frameworks in other languages. It supports test automation, sharing of setup and shutdown code for tests, aggregation of tests into collections, and independence of the tests from the reporting framework.

What do these concepts mean?
* test fixture
* test case
* test suite
* test runner

**Comment by ns-rse** [comment]
I use `pytest` but only because its the framework used when I learnt about writing tests. I've never used `unittest` to be able to give a comparison.

Features I like about `pytest`...

+ Plugins, there are lots, for coverage [pytest-cov](https://pypi.org/project/pytest-cov/), Matplotlib [pytest-mpl](https://pypi.org/project/pytest-mpl/), regression testing [pytest-regtest](https://pypi.org/project/pytest-regtest/), parallel testing [pytest-xdist](https://pypi.org/project/pytest-xdist/) and [more](https://docs.pytest.org/en/7.2.x/how-to/plugins.html).
+ [Test fixtures](https://docs.pytest.org/en/7.2.x/explanation/fixtures.html) which provide consistent context/input for tests, whether these are instantiated classes with certain properties which are reused across tests or parameterisation.
+ Simple [parameterisation](https://docs.pytest.org/en/7.2.x/how-to/parametrize.html) using `@pytest.mark.parametrize()` fixture where you define various inputs and expected outputs which are passed into the test. 

I'd be curious to find out more about `unittest` but having learnt and being  familiar with `pytest` would be reluctant to switch (acquired knowledge and learning curve both being barriers to doing so).


My understanding is that a "_test suite_" is simply an existing set of tests for a given set of code.

Not sure about "_test runner_" the [`pytest-runner`](https://pypi.org/project/pytest-runner/) extension/plugin is deprecated but appears to be a package that runs `pytest` automatically on a package. No idea of its meaning in other frameworks.

**Comment by ns-rse** [comment]
Pytest Plugins for Flask testing...

+ [pytest-flask](https://pytest-flask.readthedocs.io/en/latest/)
+ [jeancochrane/pytest-flask-sqlalchemy: A pytest plugin for preserving test isolation in Flask-SQLAlchemy using database transactions.](https://github.com/jeancochrane/pytest-flask-sqlalchemy) (nee [pytest-flask-sqlalchemy-transactions](https://pypi.org/project/pytest-flask-sqlalchemy-transactions/))


I've never used Flask so can't comment on how useful they are for testing but still love using `pytest` for my test development and use various [plugins](https://docs.pytest.org/en/latest/reference/plugin_list.html) (of which there are lots) such as [pytest-regtest](https://gitlab.com/uweschmitt/pytest-regtest) (although they've an [issue](https://gitlab.com/uweschmitt/pytest-regtest/-/issues/19) concerning dependency on `py` which I suggested a solution for over a year ago but hasn't been accepted or closed), [pytest-mpl](https://pytest-mpl.readthedocs.io/en/latest/) and [pytest-github-actions-annotate-failures](https://github.com/pytest-dev/pytest-github-actions-annotate-failures).

**Comment by ns-rse** [comment]
[Conditional coverage](https://github.com/wemake-services/coverage-conditional-plugin) if you only want to calculate these statistics under certain conditions.

**Comment by ns-rse** [comment]
Just in time...

[Pytest vs. Unittest: Which Is Better? | The PyCharm Blog](https://blog.jetbrains.com/pycharm/2024/03/pytest-vs-unittest/)

**Comment by Joe-Heffer-Shef** [comment]
Pytest Parameterisation by Neil
https://blog.nshephard.dev/posts/pytest-param/

**Comment by Joe-Heffer-Shef** [comment]
Parallel test execution with `pytest-xdist`
https://pytest-xdist.readthedocs.io/

**Comment by ns-rse** [comment]
Lots of useful Pytest extensions including...

+ [pytest-regtest](https://gitlab.com/uweschmitt/pytest-regtest) for regression testing.
+ [pytest-dependency](https://github.com/RKrahl/pytest-dependency) managing dependencies of tests.
+ [pytest-order](https://github.com/pytest-dev/pytest-order) for defining the order of tests.

**Comment by ns-rse** [comment]
Additional ways of testing.

+ [Hypothesis](https://hypothesis.readthedocs.io/en/latest/)
+ [doctest](https://docs.python.org/3/library/doctest.html) write examples in your docstrings and have them checked.

**Comment by tdjames1** [comment]
## Fixtures and mocking

- Fixture only needs to be instantiated once then can use it elsewhere
- Mocking allows simulation of server type responses
- A lot of web frameworks have testing setup
- End to end testing using selenium

https://docs.python.org/3/library/unittest.html#class-and-module-fixtures

## Parameterisation

- Subtests in unittest https://docs.python.org/3/library/unittest.html#distinguishing-test-iterations-using-subtests
- Parameterisation in unittest not as neat as in pytest

## Keeping tests small

- Run locally first

## Order of evaluation

- https://pytest-ordering.readthedocs.io/en/develop/
- https://pypi.org/project/pytest-order/
- https://pypi.org/project/pytest-dependency/

## Regression testing

Regression test plugin
https://gitlab.com/uweschmitt/pytest-regtest

https://github.com/CITCOM-project/CausalTestingFramework

"Regression testing is a common technique to implement basic testing
before refactoring legacy code that lacks a test suite."

## Other testing frameworks are available

https://hypothesis.readthedocs.io/en/latest/
https://docs.python.org/3/library/doctest.html

**Comment by twinkarma** [comment]
Covered
